name: 32BIT CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Aivle-32bit/32bit-FE
          token: ${{ secrets.CONFIG_TOKEN }}
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: build

  Deploy_Frontend:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Aivle-32bit/32bit-FE
          token: ${{ secrets.CONFIG_TOKEN }}
          submodules: true

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: build

      - name: Deploy frontend to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "#### Enter the frontend deployment section ####"
            
            FRONTEND_DIR=/home/ubuntu/frontend

            echo "#### Creating frontend directory on server ####"
            ssh -i ${{ secrets.GCP_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p $FRONTEND_DIR"

            echo "#### Uploading build files ####"
            scp -i ${{ secrets.GCP_KEY }} -r build/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:$FRONTEND_DIR

            echo "#### Restarting frontend service ####"
            ssh -i ${{ secrets.GCP_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart frontend.service"

            echo "#### Deployment complete ####"
