name: 32BIT CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CONFIG_TOKEN }}
          submodules: true

      - name: Ensure frontend directory exists
        run: mkdir -p frontend
        working-directory: ${{ github.workspace }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build React app
        run: npm run build
        working-directory: frontend

  Deploy_Frontend:
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CONFIG_TOKEN }}
          submodules: true

      - name: Deploy frontend to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "#### Enter the frontend deployment section ####"
            
            REPO_URL=${{ github.repository_url }}
            BRANCH=${{ github.ref_name }}
            FRONTEND_DIR=/home/ubuntu/frontend

            echo "#### Cloning repository ####"
            git clone --branch $BRANCH $REPO_URL $FRONTEND_DIR

            echo "#### Moving to frontend directory ####"
            cd $FRONTEND_DIR/frontend

            echo "#### Installing dependencies ####"
            npm install

            echo "#### Building React app ####"
            npm run build

            echo "#### Deployment complete ####"
