name: 32BIT CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CONFIG_TOKEN }}
          submodules: true

      - name: Ensure frontend directory exists
        run: mkdir -p frontend
        working-directory: ${{ github.workspace }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build React app
        run: npm run build
        working-directory: frontend

      - name: Check frontend directory contents
        run: ls -la frontend
        working-directory: ${{ github.workspace }}

  Deploy_Frontend:
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CONFIG_TOKEN }}
          submodules: true

      - name: Copy frontend folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "frontend"
          target: "/home/ubuntu"
          rm: true

      - name: Deploy and build React app on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "#### Enter the frontend deployment section ####"
            
            FRONTEND_DIR=/home/ubuntu/frontend
            TARGET_DIR=/home/ubuntu/frontend

            echo "#### Creating target directory if it doesn't exist ####"
            mkdir -p $TARGET_DIR

            echo "#### Moving to frontend directory ####"
            cd $FRONTEND_DIR

            echo "#### Installing dependencies ####"
            npm install

            echo "#### Building React app ####"
            npm run build

            echo "#### Copying build files to target directory ####"
            rm -rf $TARGET_DIR/*
            cp -r build/* $TARGET_DIR/
